# Generated by Django 4.2.3 on 2023-08-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RU_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
