# Generated by Django 4.2.3 on 2023-08-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RU_home', '0002_pessoa_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('tipoRefeicao', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('pratoId', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numPedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('horario', models.DateTimeField(auto_now=True)),
                ('senha', models.CharField(default='Default', max_length=100)),
                ('formPag', models.CharField(max_length=10)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RU_home.cardapio')),
            ],
        ),
        migrations.AddField(
            model_name='cardapio',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RU_home.prato'),
        ),
    ]
